GET  http://localhost/test/hs/infobase

###
# bad headers
POST  http://localhost/test/hs/epf/switch
token: token
value: on

###
POST  http://localhost/test/hs/epf/switch
token: token
value: on

###

POST  http://localhost/test/hs/epf/switch
token: token
value: off
###

POST  http://localhost/test/hs/epf/upload
token: token
name: %D0%AD%D1%82%D0%BE%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B02.epf


