openapi: 3.0.1
info:
  title: Внешние отчеты и обработки (endpoint)
  description: 'Управление внешними отчетами и обработками через HTTP сервис (REST).'
  contact:
    email: a.strizhachuk@yandex.ru
  version: 2.0.0
servers:
- url: http://localhost/test/hs
  description: develop
paths:
  /infobase:
    get:
      summary: Сведения об информационной базе
      operationId: infobase
      responses:
        200:
          description: Сведения об информационной базе
          content:
            application/json:
              schema:
                type: object
                properties:
                  config_version:
                    type: string
                  connection_string:
                    type: string
              examples:
                foo:
                  summary: Сведения об информационной базе
                  value: {
                    "config_version": "1.0.0",
                    "connection_string": "File=\"\/1c\/db\/epf-endpoint\";"
                  }
  /switch:
    post:
      summary: Включить/отключить функционал загрузки внешнего отчета или обработки
      operationId: switch
      parameters:
      - name: value
        in: header
        description: true - включить, false - отключить
        required: true
        schema:
          type: boolean
      requestBody:
        content: {}
        required: false
      responses:
        200:
          description: Текущее состояние
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                enabled:
                  summary: Включено
                  value: {
                    "type": "info",
                    "message": "Включено"
                  }
                disabled:
                  summary: Отключено
                  value: {
                    "type": "info",
                    "message": "Отключено"
                  }
        400:
          description: Ошибочный запрос
        401:
          description: Не авторизован
        403:
          description: Доступ закрыт
      security:
      - access_token_receiver: []
  /update:
    post:
      summary: Обновить внешний отчет или обработку
      operationId: update
      parameters:
      - name: name
        in: header
        description: Полное имя файла (с расширением)
        required: true
        schema:
          type: string
      requestBody:
        description: Внешний отчет или обработка в двоичном формате
        content:
          application/x-www-form-urlencoded:
            schema:
              format: binary
        required: true
      responses:
        200:
          description: Результат обновления
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                true:
                  summary: Обновление успешно
                  value: {
                    "type": "info",
                    "message": "Любое сообщение..."
                  }
                false:
                  summary: Обновление не произошло
                  value: {
                    "type": "error",
                    "message": "Ошибка такая-то..."
                  }
        400:
          description: Ошибочный запрос
        401:
          description: Не авторизован
        403:
          description: Доступ закрыт
        423:
          description: Функционал отключен
      security:
      - access_token_receiver: []
components:
  schemas:
    response:
      type: object
      properties:
        type:
          type: string
          enum:
          - info
          - error
        message:
          type: string
  securitySchemes:
    access_token_receiver:
      type: apiKey
      name: token
      in: header